/*
CONTAINS THE REDUX ALERT ACTION TYPES USED TO DISPLAY
AND CLEAR ALERTS IN THE REACT APPLICATION
*/


export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};